// Generated by spider on 2022-11-23 18:39:00.203704

part of 'resources.dart';

class Images {
  Images._();

  static const String bgimage = 'assets/images/bgimage.png';
  static const String nodata = 'assets/images/nodata.png';
  static const String nosearch = 'assets/images/nosearch.png';
  static const String splash = 'assets/images/splash.png';
  static const String noAvatar = 'assets/images/no_avatar.png';
}
